### PR TITLE
Fixes, big part of ManyToMany management and other features

### LINKED ISSUE #20: JSON : infinite loop problem between 2 entities that reference each.
There is a problem of no return to the Operations page after
creating an Operation that references a Label. 
It is caused when retrieving the HTTP response containing the Operation created in JSON format, there is an infinite loop problem because Labels and Operations refer to each one.

### LINKED ISSUE #21: Problem of a NULL field expected by the frontend to carry out a "GetAll" operation
There is a NULL field problem in the header of the HTTP response during a "GetAll" on the Operation entity. The field concerned is named "Link" and is needed by the frontend to carry out the operation.

### LINKED ISSUE #22: Retrieving the associated entities during a "Get" operation on an entity
During the "Get" operation on an entity, the fields concerning the entities it references are empty. This, need to study the behavior of Hibernate / JPA in the Java SampleApp to fetch the data and reproduce it. 
More precisely : 
1) In a first time we need to analyse the nesting level of the retrieved related entities defined by the different types of association during a query to the database.
2) In a second time we need to find how to reproduce this behavior in .Net and implement it.

### LINKED ISSUE #23: Problem on Update operation that doesn't update the relations
When making an Update on an instance of an Entity, if an association between the instance and a referenced entity is asked to be modify, nothing is done.  
For example, in an Operation referencing a BankAccount, try to change the BankAccount.
It is always the same, nothing has changed !

### PR DESCRIPTION
**Pull request by BananeGuimauve**
Like said in the title, this PR contains :
- Some fixes which close #20, close #21, close #22, close #23 
- A big part of the ManyToMany management. Only the case of the Delete operation is missing.
- Some other features detailed in the commits

### CODE REVIEW

File: src/JHipsterNetSampleApplication/Controllers/BankAccountController.cs [hunk 1]
```diff
@@ -73,9 +75,9 @@ public ActionResult<IEnumerable<BankAccount>> GetAllBankAccounts(IPageable pagea
         public async Task<IActionResult> GetBankAccount([FromRoute] long id)
         {
             _log.LogDebug($"REST request to get BankAccount : {id}");
-            var result =
-                await _applicationDatabaseContext.BankAccounts.SingleOrDefaultAsync(bankAccount =>
-                    bankAccount.Id == id);
+            var result = await _applicationDatabaseContext.BankAccounts
+                .Include(bankAccount => bankAccount.User)
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Controllers/BankAccountController.cs:79]: Just asking (I didn't test it) if we can 
1- to the filter condition (SingleOrDefaultAsync)
2- the projection (Include)
It makes more sense to me to do it in this order.

File: src/JHipsterNetSampleApplication/Controllers/LabelController.cs [hunk 2]
```diff
@@ -64,7 +64,8 @@ public async Task<IActionResult> UpdateLabel([FromBody] Label label)
         public ActionResult<IEnumerable<Label>> GetAllLabels(IPageable pageable)
         {
             _log.LogDebug("REST request to get a page of Labels");
-            var page = _applicationDatabaseContext.Labels.UsePageable(pageable);
+            var page = _applicationDatabaseContext.Labels
+                .UsePageable(pageable);
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Controllers/LabelController.cs:68]: You did the newline on-purpose or it's the IDE formatting?

File: src/JHipsterNetSampleApplication/Controllers/OperationController.cs [hunk 3]
```diff
@@ -70,8 +75,11 @@ public ActionResult<IEnumerable<Operation>> GetAllOperations(IPageable pageable)
         public async Task<IActionResult> GetOperation([FromRoute] long id)
         {
             _log.LogDebug($"REST request to get Operation : {id}");
-            var result =
-                await _applicationDatabaseContext.Operations.SingleOrDefaultAsync(operation => operation.Id == id);
+            var result = await _applicationDatabaseContext.Operations
+                .Include(operation => operation.BankAccount)
+                    .ThenInclude(bankAccount => bankAccount.User)
+                .Include("OperationLabels.Label")
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Controllers/OperationController.cs]: Either we use the lambda notation (ie. `operation => operation.BankAccount`) or the string one (ie. `"OperationLabels.Label"`) but please choose one. We must stay consistent.

File: src/JHipsterNetSampleApplication/Data/ApplicationDatabaseContext.cs [hunk 4]
```diff
@@ -43,6 +44,17 @@ protected override void OnModelCreating(ModelBuilder builder)
                 .HasForeignKey(e => e.UserId)
                 .IsRequired()
                 .OnDelete(DeleteBehavior.Cascade);
+
+            builder.Entity<OperationLabel>()
+                .HasKey(t => new { t.OperationId, t.LabelId });
+
+            builder.Entity<OperationLabel>()
+                .HasOne(pt => pt.Operation)
+                .WithMany("OperationLabels");
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Data/ApplicationDatabaseContext.cs]: If possible I would rather use the lambda/class notation because you have a compiler (and visible IDE) error if you have a typo. String are too tricky.

File: src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs [hunk 5]
```diff
@@ -33,5 +34,63 @@ private static PropertyInfo GetKeyProperty(Type type)
...
             return null;
         }
-    }
+
+        public static void RemoveNavigationProperty<TEntity, TOwnerEntity>(this DbSet<TEntity> receiver, TOwnerEntity ownerEntity, object id)
+            where TEntity : class
+            where TOwnerEntity : class
+        {
+            bool success;
+            var receiverObjects = receiver.ApplyWhere(ownerEntity.GetType().Name + "Id", id, out success);
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs]: Can we avoid the `out` usage? It's tricky and error prone. I'm not a huge fan but you can still try to convince me 😄

File: src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs [hunk 6]
```diff
@@ -33,5 +34,63 @@ private static PropertyInfo GetKeyProperty(Type type)
...
+
+            if (success) {
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs]: What if `success` is false?

File: src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs [hunk 7]
```diff
@@ -33,5 +34,63 @@ private static PropertyInfo GetKeyProperty(Type type)
...
+                    receiver.Remove(receiverObject);
+                }
+            }            
+        }
+
+        private static IQueryable<T> ApplyWhere<T>(this IQueryable<T> source, string propertyName, object propertyValue, out bool success)
+            where T : class
+        {
+            // 1. Retrieve member access expression
+            success = false;
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs]: Throw a technical Exception you have to catch on `RemoveNavigationProperty`  or play with a `java.util.Optional` .Net equivalent rather than using `out`

File: src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs [hunk 8]
```diff
@@ -0,0 +1,6 @@
+
+namespace JHipsterNetSampleApplication.Models.Interfaces {
+    public interface IJoinEntity<TEntity> {
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs]: `IJoinEntity` vs `IJoinedEntity`?

File: src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs [hunk 9]
```diff
@@ -0,0 +1,6 @@
...
+        TEntity Navigation { get; set; }
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs]: `Navigation` vs `Join`? What makes more sense?

File: src/JHipsterNetSampleApplication/Models/Label.cs [hunk 10]
```diff
@@ -2,11 +2,14 @@
 using System.Collections.Generic;
 using System.ComponentModel.DataAnnotations;
 using System.ComponentModel.DataAnnotations.Schema;
+using JHipsterNetSampleApplication.Models.RelationshipTools;
 using Newtonsoft.Json;
 
 namespace JHipsterNetSampleApplication.Models {
     [Table("label")]
     public class Label {
+        public Label() => Operations = new JoinListFacade<Operation, Label, OperationLabel>(this, OperationLabels);
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Models/Label.cs]: The constructor should be after the properties definition Line31

File: src/JHipsterNetSampleApplication/Models/Operation.cs [hunk 11]
```diff
@@ -6,13 +7,17 @@
 namespace JHipsterNetSampleApplication.Models {
     [Table("operation")]
     public class Operation {
+        public Operation()
+        {
+            Labels = new JoinListFacade<Label, Operation, OperationLabel>(this, OperationLabels);
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Models/Operation.cs]: Either your use the inline notation like [Label#new](https://github.com/jhipster/jhipster-net-sample-app-template/pull/24/files#diff-7b250f2e701b3f6910d9eac7f425c4c5R11) or the curly bracket style like here.
Please use a convention.

File: src/JHipsterNetSampleApplication/Models/RelationshipTools/JoinListFacade.cs [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+
+        public JoinListFacade(
+            TOtherEntity ownerEntity,
+            IList<TJoinEntity> list)
+        {
+            _ownerEntity = ownerEntity;
+            _list = list;
+        }
+
+        public IEnumerator<TEntity> GetEnumerator()
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Models/RelationshipTools/JoinListFacade.cs]: if you use `=>` the statement should be on the same line otherwise use `{ ... }`

File: src/JHipsterNetSampleApplication/Web/Rest/Utilities/PaginationUtil.cs [hunk 13]
```diff
@@ -31,7 +31,7 @@ public static IHeaderDictionary GeneratePaginationHttpHeaders<T>(IPage<T> page,
 
             link += $"<{GenerateUri(baseUrl, lastPage, page.Size)}>; rel=\"last\",";
             link += $"<{GenerateUri(baseUrl, 0, page.Size)}>; rel=\"first\"";
-            headers.Add(HeaderNames.From, link);
+            headers.Add("Link", link);
```
Comment (danielpetisme) [inline src/JHipsterNetSampleApplication/Web/Rest/Utilities/PaginationUtil.cs]: Create a constant for `Link`.

File: test/JHipsterNetSampleApplication.Test/Web/Rest/LabelResourceIntTest.cs [hunk 14]
```diff
@@ -93,6 +94,39 @@ public async Task CreateLabelWithExistingId()
...
+            var databaseSizeBeforeCreate = _applicationDatabaseContext.Labels.Count();
+
+            // Create the Label
+            var response = await _client.PostAsync("/api/labels", TestUtil.ToJsonContent(_label));
+            response.StatusCode.Should().Be(HttpStatusCode.Created);
+            var testLabel = _applicationDatabaseContext.Labels.ToList()[0];
+
+            // Create an Operation to test the ManyToMany association
+            var operation = new Operation {
+                Date = DateTime.UnixEpoch,
```
Comment (danielpetisme) [inline test/JHipsterNetSampleApplication.Test/Web/Rest/LabelResourceIntTest.cs]: Use `Now` rather than `Epoch`

File: test/JHipsterNetSampleApplication.Test/Web/Rest/OperationResourceIntTest.cs [hunk 15]
```diff
@@ -120,6 +120,38 @@ public async Task CreateOperationWithExistingReferencedEntity()
             testOperation.BankAccount.Should().Be(bankAccount);
         }
 
+        [Fact]
+        public async Task CreateOperationWithManyToManyAssociation()
```
Comment (danielpetisme) [inline test/JHipsterNetSampleApplication.Test/Web/Rest/OperationResourceIntTest.cs:129]: Can you test the other side of the navigation too.
Currently
- An object `_operation` exists
- You create a label . and persist it
- Add the label to the `_operation` object and persist it.
- Validation the operation
To add
- Retrieve the label from the DB including the operations
_ Verify the associated operation is the one tested above

File: test/JHipsterNetSampleApplication.Test/Web/Rest/OperationResourceIntTest.cs [hunk 16]
```diff
@@ -120,6 +120,38 @@ public async Task CreateOperationWithExistingReferencedEntity()
...
+            // Set the referencing field
+            _operation.Labels.Add(label);
+
+            // Create the Operation
+            var response = await _client.PostAsync("/api/operations", TestUtil.ToJsonContent(_operation));
+            response.StatusCode.Should().Be(HttpStatusCode.Created);
+
+            // Validate the Operation in the database
+            var operationList = _applicationDatabaseContext.Operations
+                .Include("OperationLabels.Label")
```
Comment (danielpetisme) [inline test/JHipsterNetSampleApplication.Test/Web/Rest/OperationResourceIntTest.cs]: Use the lambda/class notation

File: test/JHipsterNetSampleApplication.Test/Web/Rest/LabelResourceIntTest.cs [hunk 17]
```diff
@@ -204,5 +238,64 @@ public async Task UpdateNonExistingLabel()
...
+            };
+            secondOperation.Labels.Add(updatedLabel);
+            _applicationDatabaseContext.Operations.Add(secondOperation);
+            await _applicationDatabaseContext.SaveChangesAsync();
+            secondOperation = await _applicationDatabaseContext.Operations
+                .SingleOrDefaultAsync(o => o.Id == secondOperation.Id);
+
+            // Validate the Label in the database
+            var labelList = _applicationDatabaseContext.Labels
+                .Include("OperationLabels.Operation")
```
Comment (danielpetisme) [inline test/JHipsterNetSampleApplication.Test/Web/Rest/LabelResourceIntTest.cs]: Use the lambda/class notation

File: test/JHipsterNetSampleApplication.Test/Web/Rest/LabelResourceIntTest.cs [hunk 18]
```diff
@@ -93,6 +94,39 @@ public async Task CreateLabelWithExistingId()
...
+                Amount = new decimal(1.0)
+            };
+            operation.Labels.Add(testLabel);
+            _applicationDatabaseContext.Operations.Add(operation);
+            await _applicationDatabaseContext.SaveChangesAsync();
+            operation = _applicationDatabaseContext.Operations.ToList()[0];
+
+            // Validate the Label in the database
+            var labelList = _applicationDatabaseContext.Labels
+                .Include("OperationLabels.Operation")
```
Comment (danielpetisme) [inline test/JHipsterNetSampleApplication.Test/Web/Rest/LabelResourceIntTest.cs]: Use the lambda/class notation

**Review by danielpetisme — CHANGES_REQUESTED** [review]
Awesome work!
The test should be completed to guarantee the 2-way navigation but it smells already very good.
I've some cosmetic concerns (again :smile).

**Comment by danielpetisme** [comment]
Oh and BTW, the commit logs seems corrupted. You are including the commits of your last PR...

File: src/JHipsterNetSampleApplication/Controllers/BankAccountController.cs (hunk 1 above)
Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Controllers/BankAccountController.cs:79]: Yes, I agree with you, I tested it and it doesn't work.
It is always in this order with LINQ queries.

File: src/JHipsterNetSampleApplication/Controllers/OperationController.cs (hunk 3 above)
Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Controllers/OperationController.cs]: We are forced to do so on this property "OperationLabels". That's the only way to fetch the Labels from the database in a query.
It's a bit tricky but the field is private to hide the join entity to the user and make its management more transparent. So to access it we can only call it in a string argument. Moreover, we can't call the Labels field in the query because it is not mapped to the database.
If you prefer we can turn it to public for consistency using lambda notation and add a [JsonIgnore] annotation to hide it to the frontend ?

File: src/JHipsterNetSampleApplication/Controllers/LabelController.cs (hunk 2 above)
Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Controllers/LabelController.cs:68]: I think it's me because I saw everywhere the queries on this format : 
```
var result = await _applicationDatabaseContext.Operations
                .Include(operation => operation.BankAccount)
                    .ThenInclude(bankAccount => bankAccount.User)
                .Include("OperationLabels.Label")
```
I thought it was more readable so I made these changes. I can find them and undo it if you prefer ?

Comment (danielpetisme) [reply src/JHipsterNetSampleApplication/Controllers/LabelController.cs:68]: You're right the newline is better. I anticipate the code generation and the 
```
dbContext.{{Entity}}
//Includes
.Include({{OtherEntity}})
.ThenInclude({{AnotherOne}})
//Termination
{{UsePageable}}
```

File: src/JHipsterNetSampleApplication/Controllers/OperationController.cs (hunk 3 above)
Comment (danielpetisme) [reply src/JHipsterNetSampleApplication/Controllers/OperationController.cs]: Several options (sorted by preference)
- you turn it public 
- define constants `LABEL_ENTITY_NAME = "OperationLabels.Label"`& `OPERATION_ENTITY_NAME = "OperationLabels.Operation"` in the join entity
- compute it by reflection
- you define generic constants in the Join Entity (I don't like this approach)

Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Controllers/OperationController.cs]: Ok I turned it to public ;)

File: src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs (hunk 8 above)
Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs]: I changed to IJoinedEntity

File: src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs (hunk 9 above)
Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Models/Interfaces/IJoinEntity.cs]: I changed to Join

File: src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs (hunk 5 above)
Comment (BananeGuimauve) [reply src/JHipsterNetSampleApplication/Data/Extensions/DbSetExtensions.cs]: I used try catch and exceptions throws and tried to adding logs but I'm not really sure of how works Serilog. I will PR again, can you tell me if it is right ?
